name: workflow Context

on:
 push:
 workflow_dispatch:

env:
 MY_VAR: "workflow"

jobs:
 echo-context:
  runs-on: ubuntu-latest
  env:
   MY_VAR: "jobs"
  steps:
   - name: Display the info
     
     run: |
       echo "Event name ${{github.event_name}}"
       echo "SHA  value ${{github.sha}}"
       echo "Ref value ${{github.ref}}"
       echo "Actor ${{github.actor}}"
       echo "Workflow ${{github.workflow}}"
       echo "Runner name ${{github.run_number}}"
       echo "Runner id ${{github.run_id}}"
       echo "Print env value for the key ${{MY_VAR}}"
      
      
      
