name: workflow Context

on:
 push:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false

env:
 MY_VAR: "workflow"

jobs:
 echo-context:
  runs-on: ubuntu-latest
  env:
   MY_VAR: "jobs"
  steps:
   - name: Display the info
     env:
       MY_VAR: "steps"

     run: |
       echo "Event name ${{github.event_name}}"
       echo "SHA  value ${{github.sha}}"
       echo "Ref value ${{github.ref}}"
       echo "$GIThub_REF"
       echo "Actor ${{github.actor}}"
       echo "Workflow ${{github.workflow}}"
       echo "Runner name ${{github.run_number}}"
       echo "Runner id ${{github.run_id}}"
       echo "Print env value for the key ${{env.MY_VAR}}"
      
      
      
