name: 1- Building the workflow

on: 
 push:
 workflow_dispatch: 
 

jobs:
  echo-hello-world:
    runs-on:
      ubuntu-latest
    steps:
      - run: echo "Hello World"
  echo-say-good-bye:
    runs-on:
      windows-latest
    steps:
     - run: echo "Good bye"
     
