name: Secret Workflow

on:
 push:
 workflow_dispatch:
jobs:
 echo-secret:
  runs-on: ubuntu-latest
  steps:
   - name: Make an API Authentication Request
     env:
      API_Key: ${{secrets.API_Key}}
     run: |
      echo "Authorization : Bearer $API_KEY"
      
